import React from '../../../../node_modules/.pnpm/react@18.3.1/node_modules/react';
import { CSS } from '../utils/objectToCss';
interface Props {
    css?: CSS;
    id?: string;
    label?: React.ReactNode;
    cols?: number;
    rows?: number;
    tabIndex?: number;
    wrap?: string;
    autoCapitalize?: string;
    isErrored?: boolean;
    isRequired?: boolean;
    isDisabled?: boolean;
    isReadOnly?: boolean;
    validationState?: 'valid' | 'invalid';
    description?: React.ReactNode;
    placeholder?: string;
    value?: string;
    defaultValue?: string;
    helperText?: string;
    autoComplete?: string;
    maxLength?: number;
    minLength?: number;
    wordCount?: boolean;
    name?: string;
    pattern?: string;
    excludeFromTabOrder?: boolean;
    errorMessage?: string;
    textareaRef?: React.RefObject<HTMLTextAreaElement>;
    onChangeEvent?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
    onChange?: (value: string) => void;
    onCopy?: React.ClipboardEventHandler<HTMLTextAreaElement>;
    onCut?: React.ClipboardEventHandler<HTMLTextAreaElement>;
    onPaste?: React.ClipboardEventHandler<HTMLTextAreaElement>;
    onCompositionStart?: React.CompositionEventHandler<HTMLTextAreaElement>;
    onCompositionEnd?: React.CompositionEventHandler<HTMLTextAreaElement>;
    onCompositionUpdate?: React.CompositionEventHandler<HTMLTextAreaElement>;
    onSelect?: React.ReactEventHandler<HTMLTextAreaElement>;
    onBeforeInput?: React.FormEventHandler<HTMLTextAreaElement>;
    onInput?: React.FormEventHandler<HTMLTextAreaElement>;
    onFocus?: (e: React.FocusEvent) => void;
    onBlur?: (e: React.FocusEvent) => void;
    onKeyDown?: (e: React.KeyboardEvent) => void;
    onKeyUp?: (e: React.KeyboardEvent) => void;
    autoFocus?: boolean;
    'aria-activedescendant'?: string;
    'aria-autocomplete'?: 'none' | 'inline' | 'list' | 'both';
    'aria-haspopup'?: boolean | 'false' | 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
    'aria-controls'?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
    'aria-details'?: string;
    'aria-errormessage'?: string;
    variant?: 'h5' | string;
    resizable?: boolean;
}
export type TextareaProps = Props & Omit<React.HTMLAttributes<HTMLDivElement>, keyof Props>;
declare const Textarea: React.ForwardRefExoticComponent<Props & Omit<React.HTMLAttributes<HTMLDivElement>, keyof Props> & React.RefAttributes<HTMLDivElement>>;
export default Textarea;
