import { Content, JSONContent } from '@tiptap/react';
import React from '../../../../node_modules/.pnpm/react@18.3.1/node_modules/react';
import { CSS } from '../utils/objectToCss';
import * as controls from './controls';
import Control from './controls/Control';
import ControlsGroup from './controls/ControlsGroup';
import Toolbar from './toolbar';
interface Props {
    children?: React.ReactNode;
    outputType?: 'html' | 'json';
    characterCount?: number | null;
    onChange?: (html: string | JSONContent) => void;
    isEditable?: boolean;
    content?: Content;
    placeholder?: string;
    className?: string;
    css?: CSS;
}
export type RichTextEditorProps = Props & Omit<React.HTMLAttributes<HTMLDivElement>, keyof Props>;
declare const _default: React.ForwardRefExoticComponent<Props & Omit<React.HTMLAttributes<HTMLDivElement>, keyof Props> & React.RefAttributes<HTMLDivElement>> & {
    Control: typeof Control;
    ControlsGroup: typeof ControlsGroup;
    Toolbar: typeof Toolbar;
    Bold: typeof controls.BoldControl;
    Italic: typeof controls.ItalicControl;
    Strikethrough: typeof controls.StrikeThroughControl;
    Underline: typeof controls.UnderlineControl;
    H1: typeof controls.H1Control;
    H2: typeof controls.H2Control;
    H3: typeof controls.H3Control;
    H4: typeof controls.H4Control;
    H5: typeof controls.H5Control;
    H6: typeof controls.H6Control;
    BulletList: typeof controls.BulletListControl;
    OrderedList: typeof controls.OrderedListControl;
    Link: typeof controls.LinkControl;
    Unlink: typeof controls.UnlinkControl;
    Image: typeof controls.ImageControl;
    Blockquote: typeof controls.BlockquoteControl;
    AlignLeft: typeof controls.AlignLeftControl;
    AlignRight: typeof controls.AlignRightControl;
    AlignCenter: typeof controls.AlignCenterControl;
    AlignJustify: typeof controls.AlignJustifyControl;
    Superscript: typeof controls.SuperscriptControl;
    Subscript: typeof controls.SubscriptControl;
    CodeBlock: typeof controls.CodeBlockControl;
    ColorControl: typeof controls.ColorControl;
    HeadingsControl: typeof controls.HeadingsControl;
    TextAlginmentSelector: typeof controls.TextAlignmentSelectorControl;
    Hr: typeof controls.HrControl;
    Undo: typeof controls.UndoControl;
    Redo: typeof controls.RedoControl;
};
export default _default;
