import {Typography} from '@comfortdelgro/react-compass'
import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Typography.Header variant='header1' css={{textAlign: 'center'}}>
          Welcome to Next.js!
        </Typography.Header>

        <Typography.Header variant='header3' css={{textAlign: 'center'}}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </Typography.Header>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <Typography.Header variant='header4'>
              Documentation &rarr;
            </Typography.Header>
            <Typography.Label variant='label3'>
              Find in-depth information about Next.js features and API.
            </Typography.Label>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <Typography.Header variant='header4'>
              Learn &rarr;
            </Typography.Header>
            <Typography.Label variant='label3'>
              Learn about Next.js in an interactive course with quizzes!
            </Typography.Label>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className={styles.card}
          >
            <Typography.Header variant='header4'>
              Examples &rarr;
            </Typography.Header>
            <Typography.Label variant='label3'>
              Discover and deploy boilerplate example Next.js projects.
            </Typography.Label>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <Typography.Header variant='header4'>
              Deploy &rarr;
            </Typography.Header>
            <Typography.Label variant='label3'>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Typography.Label>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
