name: Release

on:
  push:
    branches:
      - feature/h5-optimization
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (e.g., h5)'
        required: true
        default: ''

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Bot
        run: |
          git config --global user.email "services.shared@zig.live"
          git config --global user.name "CDG Zig Bot"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run --filter=@comfortdelgro/react-compass build

      - name: Bump version manually
        if: github.event_name == 'workflow_dispatch'
        run: |
          CUSTOM_VERSION=${{ github.event.inputs.release_name }}
          echo "Custom version: $CUSTOM_VERSION"
          # Update the version in package.json
          npm version $CUSTOM_VERSION --no-git-tag-version

      - name: Commit version change
        if: github.event_name == 'workflow_dispatch'
        run: |
          git add package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.release_name }}"

      - name: Push changes
        if: github.event_name == 'workflow_dispatch'
        run: |
          git push origin HEAD:main

      - name: Publish to NPM
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CDG_PUBLISHER_NPM_TOKEN }}
