name: Release

on:
  push:
    branches:
      - feature/h5-optimization
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Bot
        run: |
          git config --global user.email "services.shared@zig.live"
          git config --global user.name "CDG Zig Bot"
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      
      - name: Build
        run: pnpm run --filter=@comfortdelgro/react-compass build

      - name: Bump version to 3.3.0-h5
        run: |
          CUSTOM_VERSION="3.3.0-h5"
          echo "Custom version: $CUSTOM_VERSION"
          # Update the version in package.json
          pnpm version $CUSTOM_VERSION
      
      - name: Commit version change
        run: |
          git add package.json
          git commit -m "chore: bump version to 3.3.0-h5" || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git push origin HEAD:feature/h5-optimization || echo "No changes to push"
      
      - name: Publish to NPM
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.CDG_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.CDG_PUBLISHER_NPM_TOKEN }}
